### PR TITLE
Setup repo for Scout24

### PR DESCRIPTION
**Pull request by nisrulz**
- Followed the setup from Form flow repo [here](https://github.com/Scout24/android-formflow)
- Using modified version of [Jenkinsfile.prb](https://github.com/Scout24/android-formflow/blob/master/Jenkinsfile.prb) and [Jenkinsfile.publish](https://github.com/Scout24/android-formflow/blob/master/Jenkinsfile.publish) for PRs and publishing respectively

### Extra
- Set repo policy to protect main branch from direct write access and allow through PRs only
- Set PR policy to be green depending on PR pipeline and at least one review approval

### CODE REVIEW

**Comment by szykam** [comment]
Pipeline is failing.

**Comment by NoyaD9** [comment]
@nisrulz metadata.yaml is not required
Public repositories **must not have** a metadata.yaml

**Comment by szykam** [comment]
With scripts created, fire up release pipeline. Now I can't see any library related in a [list](https://is24-android-fizz.fizz.cloud.scout24.com/blue/pipelines).

**Comment by nisrulz** [comment]
This fork is going away soon. So I will not update this.
Screenshot 2024-09-25 at 15 53 12

**Pull request closed without merging**
